language: node_js
node_js:
  - 8
notifications:
  email: false
os:
  - linux

before_install:
  - openssl aes-256-cbc -K $encrypted_3410a66d26c9_key -iv $encrypted_3410a66d26c9_iv
    -in travis-encrypted/fb-test-app-project-db46892688cd.json.enc
    -out travis-encrypted/fb-test-app-project-db46892688cd.json -d
  - npm install -g yarn
install:
  - yarn install

jobs:
  include:
    - script: yarn test
      name: 'Trial run for console latency test'
      if: type IN (push, pull_request)
    - script: yarn launch
      name: 'Formal run for console latency test'
      if: type = cron
